// <auto-generated />
using System;
using FirstApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstApp.Data.Migrations
{
    [DbContext(typeof(FirstAppDbContext))]
    [Migration("20200325122617_initialcreatety")]
    partial class initialcreatety
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstApp.Core.EntityTest", b =>
                {
                    b.Property<int>("id_internal")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ETag");

                    b.Property<string>("PartitionKey");

                    b.Property<string>("RowKey");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<int>("entity_type");

                    b.HasKey("id_internal");

                    b.ToTable("EntityTest");
                });

            modelBuilder.Entity("FirstApp.Core.RelationshipTest", b =>
                {
                    b.Property<int>("guid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ETag");

                    b.Property<string>("PartitionKey");

                    b.Property<string>("RowKey");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<int>("id_internal");

                    b.Property<int>("id_internal_ref");

                    b.Property<int>("typeRelationship");

                    b.HasKey("guid");

                    b.HasIndex("id_internal");

                    b.ToTable("RelationshipTest");
                });

            modelBuilder.Entity("FirstApp.Core.RestaurantDS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ETag");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("PK");

                    b.Property<string>("PartitionKey");

                    b.Property<string>("RowKey");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("FirstApp.Core.RelationshipTest", b =>
                {
                    b.HasOne("FirstApp.Core.EntityTest", "entityTest")
                        .WithMany("RelationshipTest")
                        .HasForeignKey("id_internal")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
